name: Build and Deploy Backend API

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  DOCKER_USERNAME: beekay24
  BACKEND_IMAGE: beekay24/hangul-api

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.BACKEND_IMAGE }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push backend
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max

  deploy-info:
    runs-on: ubuntu-latest
    needs: [build-backend]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
    - name: Deployment Summary
      run: |
        echo "🚀 Backend API Deployment Summary"
        echo "================================="
        echo "Backend Image: ${{ env.BACKEND_IMAGE }}:latest"
        echo ""
        echo "🐳 Docker Run Command:"
        echo "docker run -p 5250:5250 ${{ env.BACKEND_IMAGE }}:latest"
        echo ""
        echo "📊 API will be available at: http://localhost:5250"
        echo "🔗 Docker Hub: https://hub.docker.com/r/${{ env.DOCKER_USERNAME }}/hangul-api" 